"""
4.3_viscosity_sensitivity.py
============================

Section 4.3: shock-capture and viscosity-sensitivity analysis.

Goal
----
Quantify how the FNO accuracy degrades as the viscosity nu decreases (the
solutions develop sharper shocks), exposing the shock-capturing bottleneck
of a Fourier-based surrogate model.

Procedure
---------
  1. Three datasets with the SAME 1000 GRF initial conditions (Section 4.1.1)
     are used:  nu in {0.1, 0.01, 0.001}.
     - nu = 0.01 : reference solutions from Section 4.1.1,
     - nu = 0.1 and nu = 0.001 : computed by 4.3_generate_reference_solutions.py
       (validated against the Cole-Hopf exact solution).
  2. Train one FNO (L = 4, k_max = 16, d_v = 64) per viscosity on the 800
     training samples at N = 64 with identical hyper-parameters; the
     nu = 0.01 model is reused from Section 4.2.
  3. FDM baselines (Lax-Friedrichs + TVD, N = 64) are computed for nu = 0.1
     and nu = 0.001 (reusing the Section 4.1 FDM solver); the nu = 0.01 FDM
     baseline is reused from Section 4.1.3.
  4. Test-set evaluation (200 samples, N = 64): mean rel L2 / rel Linf with
     bootstrap 95% CI, per-sample errors, and the FNO-to-FDM error ratio.
  5. For nu = 0.001, snapshots of typical samples show the smoothing /
     Gibbs-type behaviour of the FNO at the shocks.

Outputs (all with the "4.3" prefix):
    data/4.3_error_metrics.csv
    data/4.3_summary.csv
    data/4.3_parameters.csv
    data/4.3_fno_nu0p1_weights.pt , data/4.3_fno_nu0p001_weights.pt
    figures/4.3_viscosity_sensitivity.png
    figures/4.3_shock_snapshots.png
    4.3_README.md

All comments and figure labels are in English.
"""

import os
import time

import numpy as np
import importlib.util

import torch
import torch.nn as nn

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ============================================================================
# 1. Configuration
# ============================================================================
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

NUS = [0.1, 0.01, 0.001]      # viscosity benchmark values
N_GRID = 64                   # FNO / FDM working resolution
N_REF = 2048                  # spectral reference resolution
N_SAMPLES = 1000
N_TRAIN = 800
N_TEST = 200

EPOCHS = 200
BATCH_SIZE = 32
LR = 1e-3
BOOT_ITER = 1000
FDM_MIN_STEPS = 400           # floor on the number of FDM time steps

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
FIG_DIR = os.path.join(BASE_DIR, "figures")

# ============================================================================
# 2. Load modules from Sections 4.1 and 4.2
# ============================================================================
def _load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

m41 = _load_module("m41", os.path.join(BASE_DIR, "4.1_fdm_comparison_baselines.py"))
m42 = _load_module("m42", os.path.join(BASE_DIR, "4.2_resolution_invariance.py"))

FNO1d = m42.FNO1d
count_params = m42.count_params
train_model = m42.train_model
bootstrap_ci = m42.bootstrap_ci

# ============================================================================
# 3. Data loading
# ============================================================================
def load_all_data():
    """Return, for every nu, the reference solutions (1000 x 2048) and split."""
    u0_all = np.loadtxt(os.path.join(DATA_DIR, "grf_initial_conditions.csv"),
                        delimiter=",", skiprows=1)
    with open(os.path.join(DATA_DIR, "train_test_split.csv")) as fh:
        lines = fh.read().splitlines()[1:]
    train_idx = np.array([i for i, ln in enumerate(lines)
                          if ln.split(",")[1] == "train"])
    test_idx = np.array([i for i, ln in enumerate(lines)
                         if ln.split(",")[1] == "test"])

    refs = {}
    # nu = 0.01: from Section 4.1.1 (train/test files)
    ref01 = np.empty_like(u0_all)
    ref01[train_idx] = np.loadtxt(os.path.join(DATA_DIR, "train",
                                               "solutions_final.csv"),
                                  delimiter=",", skiprows=1)
    ref01[test_idx] = np.loadtxt(os.path.join(DATA_DIR, "test",
                                              "solutions_final.csv"),
                                 delimiter=",", skiprows=1)
    refs[0.01] = ref01
    # nu = 0.1 and nu = 0.001: generated by 4.3_generate_reference_solutions.py
    for nu, tag in [(0.1, "nu0p1"), (0.001, "nu0p001")]:
        refs[nu] = np.loadtxt(os.path.join(
            DATA_DIR, f"4.3_reference_solutions_{tag}.csv"),
            delimiter=",", skiprows=1)
    return u0_all, refs, train_idx, test_idx


# ============================================================================
# 4. Evaluation helpers
# ============================================================================
def rel_l2_linf_batch(pred, ref):
    """Per-sample relative L2 and L-infinity errors, shapes (n, N)."""
    l2 = np.linalg.norm(pred - ref, axis=1) / np.linalg.norm(ref, axis=1)
    linf = np.max(np.abs(pred - ref), axis=1) / np.max(np.abs(ref), axis=1)
    return l2, linf


def evaluate_fno(fno, u0_test, ref_test, grid=N_GRID):
    """Zero-shot-free (same-resolution) FNO evaluation on the test set."""
    step = N_REF // grid
    X = torch.tensor(u0_test[:, ::step], dtype=torch.float32)
    y = ref_test[:, ::step]
    fno.eval()
    with torch.no_grad():
        pred = fno(X).numpy()
    return rel_l2_linf_batch(pred, y)


def _van_leer_limiter(du_b, du_f):
    """Van Leer TVD limiter (works on (B, N) arrays, axis = -1)."""
    same_sign = du_b * du_f > 0.0
    with np.errstate(divide="ignore", invalid="ignore"):
        phi = np.where(same_sign, 2.0 * du_b / (du_b + du_f + 1e-30), 0.0)
    return phi


def _fdm_rhs(u, nu, dx, dx2):
    """FDM RHS (Lax-Friedrichs flux + van Leer TVD) vectorized over samples.

    u : (B, N) batch of point values on the periodic grid.
    """
    du_f = np.roll(u, -1, axis=-1) - u              # u[j+1] - u[j]
    du_b = u - np.roll(u, 1, axis=-1)               # u[j] - u[j-1]
    u_l = u + 0.5 * _van_leer_limiter(du_b, du_f) * du_f
    u_r = np.roll(u, -1, axis=-1) - 0.5 * _van_leer_limiter(
        du_f, np.roll(du_f, -1, axis=-1)) * np.roll(du_f, -1, axis=-1)
    c = np.maximum(np.abs(u_l), np.abs(u_r))
    flux = 0.5 * (0.5 * u_l**2 + 0.5 * u_r**2) - 0.5 * c * (u_r - u_l)
    dudt = (-(flux - np.roll(flux, 1, axis=-1)) / dx
            + nu * (np.roll(u, -1, axis=-1) - 2.0 * u
                    + np.roll(u, 1, axis=-1)) / dx2)
    return dudt


def fdm_solve_batched(u0_batch, nu, dx, dt, n_steps):
    """Explicit RK4 FDM solve for a batch of initial conditions."""
    dx2 = dx * dx
    u = np.array(u0_batch, dtype=float)
    for _ in range(n_steps):
        k1 = _fdm_rhs(u, nu, dx, dx2)
        k2 = _fdm_rhs(u + 0.5 * dt * k1, nu, dx, dx2)
        k3 = _fdm_rhs(u + 0.5 * dt * k2, nu, dx, dx2)
        k4 = _fdm_rhs(u + dt * k3, nu, dx, dx2)
        u = u + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
    return u


def fdm_solve_for_nu(u0_all, ref_all, nu, train_idx, test_idx):
    """FDM baseline (N = 64) for all samples at viscosity nu (batched).

    The solution is written to a checkpoint CSV so that re-runs reuse it.
    Returns the (1000, N) FDM solution and the (1000, N) reference on the
    same grid.
    """
    tag = "nu0p1" if nu == 0.1 else "nu0p001"
    sol_path = os.path.join(DATA_DIR, f"4.3_fdm_solutions_{tag}.csv")
    refg = ref_all[:, ::N_REF // N_GRID]
    if os.path.exists(sol_path):
        sol = np.loadtxt(sol_path, delimiter=",", skiprows=1)
        print(f"  FDM nu={nu:g}: loaded from {sol_path}")
        return sol, refg, float("nan"), 0

    dx = 1.0 / N_GRID
    u0g = u0_all[:, ::N_REF // N_GRID]
    umax = np.abs(u0g).max()
    dt = m41.fdm_cfl_dt(dx, nu, umax)
    n_steps = max(int(np.ceil(m41.T_MAX / dt)), FDM_MIN_STEPS)
    dt = m41.T_MAX / n_steps
    sol = fdm_solve_batched(u0g, nu, dx, dt, n_steps)
    np.savetxt(sol_path, sol, delimiter=",", fmt="%.8e",
               header=",".join(f"{i / N_GRID:.6f}" for i in range(N_GRID)),
               comments="")
    print(f"  FDM nu={nu:g}: dt = {dt:.4e}, {n_steps} steps "
          f"(batched), saved to {sol_path}")
    return sol, refg, dt, n_steps


# ============================================================================
# 5. Figures
# ============================================================================
def plot_viscosity_sensitivity(summary, path):
    """Rel L2 error vs viscosity for FNO and FDM (log-x axis)."""
    fig, ax = plt.subplots(figsize=(7.5, 5.2))
    for method, color, marker in (("FNO", "#1f77b4", "o"),
                                  ("FDM", "#d62728", "s")):
        sub = sorted([r for r in summary if r["method"] == method],
                     key=lambda r: r["nu"])
        x = [r["nu"] for r in sub]
        y = [r["mean_rel_l2"] for r in sub]
        lo = [r["ci_low_l2"] for r in sub]
        hi = [r["ci_high_l2"] for r in sub]
        ax.plot(x, y, marker + "-", lw=1.8, color=color,
                label=f"{method} (N={N_GRID})")
        ax.fill_between(x, lo, hi, color=color, alpha=0.2,
                        label=f"{method} 95% CI")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xticks(NUS)
    ax.set_xticklabels(["$10^{-1}$", "$10^{-2}$", "$10^{-3}$"])
    ax.set_xlabel(r"Viscosity  $\nu$")
    ax.set_ylabel("Mean relative L2 error (200 test samples)")
    ax.set_title("Viscosity Sensitivity: FNO Accuracy Degradation\n"
                 "as the Shock Gets Sharper (Burgers, N = 64)")
    ax.grid(True, alpha=0.3, which="both")
    ax.legend(fontsize=9)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_shock_snapshots(u0_test, ref_test, fno, fdm_sol, nu, sample_ids, path):
    """nu = 0.001 snapshots: reference vs FNO (zero-shot @2048) vs FDM.

    Top row: full N = 2048 view (FNO evaluated at N = 2048 shows the
    smoothing of the shock).  Bottom row: zoom on the steepest region.
    """
    x_ref = np.arange(N_REF) / N_REF
    x64 = (np.arange(N_GRID) + 0.0) / N_GRID
    fig, axes = plt.subplots(2, len(sample_ids), figsize=(4.6 * len(sample_ids), 6.0))
    with torch.no_grad():
        for j, s in enumerate(sample_ids):
            X = torch.tensor(u0_test[s], dtype=torch.float32).unsqueeze(0)
            pred_fno = fno(X).numpy()[0]                # zero-shot at N=2048
            ref = ref_test[s]

            # top row: full field at N = 2048
            ax = axes[0, j]
            ax.plot(x_ref, ref, lw=1.0, color="black", label="Reference (N=2048)")
            ax.plot(x_ref, pred_fno, lw=1.0, color="#1f77b4", label="FNO (N=2048, zero-shot)")
            ax.plot(x64, fdm_sol[s], "o", ms=2.5, color="#d62728", label="FDM (N=64)")
            ax.set_title(f"Test sample {s}  ($\\nu$ = {nu:g})")
            ax.grid(True, alpha=0.3)
            if j == 0:
                ax.set_ylabel(r"$u(x,T)$")
            ax.legend(fontsize=7)

            # bottom row: zoom on the region of largest reference gradient
            grad = np.abs(np.gradient(ref))
            imax = int(np.argmax(grad))
            x0, x1 = max(0.0, x_ref[imax] - 0.12), min(1.0, x_ref[imax] + 0.12)
            m = (x_ref >= x0) & (x_ref <= x1)
            ax = axes[1, j]
            ax.plot(x_ref[m], ref[m], lw=1.3, color="black")
            ax.plot(x_ref[m], pred_fno[m], lw=1.3, color="#1f77b4")
            ax.plot(x64[(x64 >= x0) & (x64 <= x1)],
                    fdm_sol[s][(x64 >= x0) & (x64 <= x1)], "o", ms=3.0, color="#d62728")
            ax.set_xlim(x0, x1)
            ax.grid(True, alpha=0.3)
            if j == 0:
                ax.set_ylabel(r"$u(x,T)$")
            ax.set_xlabel("$x$")
    fig.suptitle("Sharp-Feature (Near-Shock) Capture at $\\nu = 0.001$: "
                 "the FNO Smoothes the Steep Gradients "
                 "(bandwidth-limited to $k_{max} = 16$)")
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    fig.savefig(path, dpi=150)
    plt.close(fig)


# ============================================================================
# 6. Main pipeline
# ============================================================================
def main():
    t_start = time.time()
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(FIG_DIR, exist_ok=True)

    print("=" * 78)
    print("Section 4.3 - shock capture and viscosity sensitivity")
    print("=" * 78)

    u0_all, refs, train_idx, test_idx = load_all_data()
    u0_test = u0_all[test_idx]
    print(f"Data: nu = {NUS}, 800 train / 200 test, N_REF = {N_REF}")

    # ---------- FNO models ----------------------------------------------------
    fnos = {}
    fno = FNO1d()
    fno.load_state_dict(torch.load(os.path.join(DATA_DIR, "4.2_fno_weights.pt")))
    fnos[0.01] = fno
    print("Reused the nu = 0.01 FNO from Section 4.2.")

    step = N_REF // N_GRID
    X_tr = torch.tensor(u0_all[train_idx][:, ::step], dtype=torch.float32)
    for nu in (0.1, 0.001):
        tag = "nu0p1" if nu == 0.1 else "nu0p001"
        wpath = os.path.join(DATA_DIR, f"4.3_fno_{tag}_weights.pt")
        if os.path.exists(wpath):
            model = FNO1d()
            model.load_state_dict(torch.load(wpath))
            print(f"Loaded FNO nu = {nu:g} from {wpath} (resume mode).")
        else:
            Y_tr = torch.tensor(refs[nu][train_idx][:, ::step],
                                dtype=torch.float32)
            model = FNO1d()
            print(f"Training FNO at nu = {nu:g} ...")
            train_model(model, X_tr, Y_tr, name=f"FNO nu={nu:g}")
            torch.save(model.state_dict(), wpath)
        fnos[nu] = model

    # ---------- FNO evaluation at N = 64 --------------------------------------
    print("FNO evaluation on the 200 test samples (N = 64) ...")
    fno_err = {}                     # nu -> (l2, linf) per-sample arrays
    for nu in NUS:
        l2, linf = evaluate_fno(fnos[nu], u0_test, refs[nu][test_idx])
        fno_err[nu] = (l2, linf)
        print(f"  FNO nu={nu:g}: rel-L2 = {l2.mean():.4e} "
              f"rel-Linf = {linf.mean():.4e}")

    # ---------- FDM baselines ---------------------------------------------------
    print("FDM baselines (Lax-Friedrichs + TVD, N = 64) ...")
    fdm_err = {}
    fdm_sol_nu = {}
    # nu = 0.01: reuse the Section 4.1.3 FDM solutions
    fdm_sol01 = np.loadtxt(os.path.join(DATA_DIR, "4.1_fdm_solutions_final.csv"),
                           delimiter=",", skiprows=1)
    fdm_sol_nu[0.01] = fdm_sol01
    ref01_64 = refs[0.01][:, ::step]
    l2, linf = rel_l2_linf_batch(fdm_sol01[test_idx], ref01_64[test_idx])
    fdm_err[0.01] = (l2, linf)
    print(f"  FDM nu=0.01 (reused): rel-L2 = {l2.mean():.4e} "
          f"rel-Linf = {linf.mean():.4e}")

    for nu in (0.1, 0.001):
        sol, refg, dt, n_steps = fdm_solve_for_nu(u0_all, refs[nu], nu,
                                                  train_idx, test_idx)
        fdm_sol_nu[nu] = sol
        l2, linf = rel_l2_linf_batch(sol[test_idx], refg[test_idx])
        fdm_err[nu] = (l2, linf)
        print(f"  FDM nu={nu:g}: dt = {dt:.4e}, {n_steps} steps, "
              f"rel-L2 = {l2.mean():.4e}, rel-Linf = {linf.mean():.4e}")

    # ---------- summaries -------------------------------------------------------
    summary = []
    for nu in NUS:
        for method, err in (("FNO", fno_err[nu]), ("FDM", fdm_err[nu])):
            l2, linf = err
            lo2, hi2 = bootstrap_ci(l2)
            lof, hif = bootstrap_ci(linf)
            summary.append({
                "nu": nu, "method": method,
                "mean_rel_l2": l2.mean(), "ci_low_l2": lo2, "ci_high_l2": hi2,
                "mean_rel_linf": linf.mean(), "ci_low_linf": lof,
                "ci_high_linf": hif,
            })
            print(f"  [{method} nu={nu:g}] L2 = {l2.mean():.4e} "
                  f"[{lo2:.4e}, {hi2:.4e}]  Linf = {linf.mean():.4e} "
                  f"[{lof:.4e}, {hif:.4e}]")

    # FNO-to-FDM error ratios
    print("-" * 78)
    for nu in NUS:
        ratio = (fno_err[nu][0].mean() / fdm_err[nu][0].mean())
        print(f"  nu={nu:g}: FNO/FDM rel-L2 ratio = {ratio:.3f}")

    # ---------- save CSVs --------------------------------------------------------
    with open(os.path.join(DATA_DIR, "4.3_error_metrics.csv"), "w") as fh:
        fh.write("sample_index,split,nu,method,rel_l2,rel_linf\n")
        for k, s in enumerate(test_idx):
            for nu in NUS:
                fh.write(f"{s},test,{nu:g},FNO,{fno_err[nu][0][k]:.8e},"
                         f"{fno_err[nu][1][k]:.8e}\n")
                fh.write(f"{s},test,{nu:g},FDM,{fdm_err[nu][0][k]:.8e},"
                         f"{fdm_err[nu][1][k]:.8e}\n")
    print(f"Saved: {os.path.join(DATA_DIR, '4.3_error_metrics.csv')}")

    # summary CSV
    with open(os.path.join(DATA_DIR, "4.3_summary.csv"), "w") as fh:
        fh.write("nu,method,mean_rel_l2,ci_low_l2,ci_high_l2,"
                 "mean_rel_linf,ci_low_linf,ci_high_linf\n")
        for r in summary:
            fh.write(f"{r['nu']:g},{r['method']},{r['mean_rel_l2']:.8e},"
                     f"{r['ci_low_l2']:.8e},{r['ci_high_l2']:.8e},"
                     f"{r['mean_rel_linf']:.8e},{r['ci_low_linf']:.8e},"
                     f"{r['ci_high_linf']:.8e}\n")
    print(f"Saved: {os.path.join(DATA_DIR, '4.3_summary.csv')}")

    # parameters CSV
    with open(os.path.join(DATA_DIR, "4.3_parameters.csv"), "w") as fh:
        fh.write("parameter,value\n")
        for key, val in [
            ("equation", "u_t + u u_x = nu*u_xx, x in [0,1), periodic BC"),
            ("viscosities", "0.1, 0.01, 0.001"),
            ("N_GRID", N_GRID), ("N_REF", N_REF),
            ("N_TRAIN", N_TRAIN), ("N_TEST", N_TEST), ("seed", SEED),
            ("fno_arch", "L=4, k_max=16, d_v=64, GELU"),
            ("training", f"Adam lr={LR}, cosine, {EPOCHS} epochs, batch {BATCH_SIZE}"),
            ("fno_nu0p01", "reused from Section 4.2 (4.2_fno_weights.pt)"),
            ("fdm", "Lax-Friedrichs + TVD (van Leer), N=64, RK4"),
            ("fdm_nu0p01", "reused from Section 4.1.3 (4.1_fdm_solutions_final.csv)"),
            ("reference", "Fourier pseudo-spectral + IF-RK4, N=2048, "
                          "validated vs Cole-Hopf"),
            ("bootstrap", f"{BOOT_ITER} resamples, 95% CI"),
        ]:
            fh.write(f"{key},{val}\n")

    # ---------- figures ----------------------------------------------------------
    plot_viscosity_sensitivity(summary, os.path.join(
        FIG_DIR, "4.3_viscosity_sensitivity.png"))

    # select the two test samples with the sharpest features at nu = 0.001
    dxr = 1.0 / N_REF
    sharpness = np.array([np.abs(np.gradient(refs[0.001][s], dxr)).max()
                          for s in test_idx])
    sharp_samples = [int(test_idx[i]) for i in
                     np.argsort(sharpness)[::-1][:2]]
    print(f"Sharpest nu=0.001 test samples for the snapshot figure: "
          f"{sharp_samples}")
    plot_shock_snapshots(u0_all, refs[0.001], fnos[0.001],
                         fdm_sol_nu[0.001], 0.001, sharp_samples,
                         os.path.join(FIG_DIR, "4.3_shock_snapshots.png"))

    # ---------- README ------------------------------------------------------------
    ratios = {nu: fno_err[nu][0].mean() / fdm_err[nu][0].mean() for nu in NUS}
    write_readme(summary, ratios, fnos)

    print("=" * 78)
    print(f"Done. Total wall-clock time: {time.time() - t_start:.1f} s")
    print("=" * 78)


def write_readme(summary, ratios, fnos):
    """Write 4.3_README.md (English)."""
    p01 = count_params(fnos[0.01])
    lines = [
        "# Section 4.3 - Shock Capture and Viscosity Sensitivity",
        "",
        "Goal: quantify how the FNO accuracy degrades as the viscosity",
        "decreases (sharper shocks), exposing the shock-capturing bottleneck",
        "of a Fourier-based surrogate model.",
        "",
        "## Setup",
        "",
        "- Three datasets with the SAME 1000 GRF initial conditions",
        "  (Section 4.1.1, seed = 42): nu in {0.1, 0.01, 0.001}.",
        "- nu = 0.01 reference from Section 4.1.1; nu = 0.1 and nu = 0.001",
        "  references solved with the validated spectral solver (N = 2048,",
        "  IF-RK4, checked against the Cole-Hopf exact solution).",
        "- One FNO per viscosity (L = 4, k_max = 16, d_v = 64), trained on the",
        "  800 training samples at N = 64 with identical hyper-parameters",
        "  (Adam lr = 1e-3, cosine schedule, 200 epochs, batch 32).",
        "- The nu = 0.01 FNO is reused from Section 4.2; the nu = 0.01 FDM",
        "  baseline is reused from Section 4.1.3.",
        f"- FNO parameter count: {p01} (stored floats).",
        "",
        "## Results (200 test samples, N = 64)",
        "",
        "| nu | method | mean rel-L2 [95% CI] | mean rel-Linf [95% CI] |",
        "|---|---|---|---|",
    ]
    for r in sorted(summary, key=lambda r: (r["nu"], r["method"]), reverse=True):
        lines.append(
            f"| {r['nu']:g} | {r['method']} | "
            f"{r['mean_rel_l2']:.3e} [{r['ci_low_l2']:.3e}, "
            f"{r['ci_high_l2']:.3e}] | "
            f"{r['mean_rel_linf']:.3e} [{r['ci_low_linf']:.3e}, "
            f"{r['ci_high_linf']:.3e}] |")
    lines += [
        "",
        "## FNO / FDM relative-L2 error ratios",
        "",
    ]
    for nu in NUS:
        lines.append(f"- nu = {nu:g}: {ratios[nu]:.3f}x")
    lines += [
        "",
        "## Files",
        "",
        "- `data/4.3_error_metrics.csv` - per-sample rel L2 / rel Linf",
        "- `data/4.3_summary.csv` - mean errors and bootstrap 95% CI",
        "- `data/4.3_parameters.csv` - experiment configuration",
        "- `data/4.3_reference_solutions_nu0p1.csv`, "
        "`data/4.3_reference_solutions_nu0p001.csv` - reference solutions",
        "- `data/4.3_reference_validation.csv` - Cole-Hopf validation of the",
        "  reference solver",
        "- `data/4.3_fno_nu0p1_weights.pt`, `data/4.3_fno_nu0p001_weights.pt`",
        "- `figures/4.3_viscosity_sensitivity.png` - error vs nu curves",
        "- `figures/4.3_shock_snapshots.png` - shock smoothing at nu = 0.001",
        "",
        "## Reproduce",
        "",
        "    python 4.3_generate_reference_solutions.py   # ~30 min, once",
        "    .venv_torch\\Scripts\\python.exe 4.3_viscosity_sensitivity.py",
    ]
    with open(os.path.join(BASE_DIR, "4.3_README.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()



